### ISSUE TITLE
バージョン指定で自動でDockerfile書き出し

### ISSUE THREAD

**Issue by a-r-g-v** [greyia/minecraft-docker#3]
したい

**Comment by aiwas** [comment]
@greyia container.conf的な設定ファイル＋生成スクリプト→一時的なDockerfileを書き出し＆それを使ってdocker buildという感じ？

**Comment by a-r-g-v** [comment]
@aiwas 設定ファイル作っても良いし，設定ファイル読みに行くよりは，CUIで{対話式,引数}で動くコマンドを自作したほうが楽そう
